[package]
name = "gulag"
version = "0.1.0"
authors = ["Steffen Haug <steffeah@stud.ntnu.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.41"
gl = "0.14"
lazy_static = "1.4"